//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectionUriDemo.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Controller_Reflection_DBEntities3 : DbContext
    {
        public Controller_Reflection_DBEntities3()
            : base("name=Controller_Reflection_DBEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tb_Controller> tb_Controller { get; set; }
        public virtual DbSet<tb_ControllerMappedRoles> tb_ControllerMappedRoles { get; set; }
        public virtual DbSet<tb_Roles> tb_Roles { get; set; }
        public virtual DbSet<tb_UserMappedRoles> tb_UserMappedRoles { get; set; }
        public virtual DbSet<tb_Users> tb_Users { get; set; }
    }
}
