//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReflectionUriDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Controller
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tb_Controller()
        {
            this.tb_ControllerMappedRoles = new HashSet<tb_ControllerMappedRoles>();
        }
    
        public int ControllerId { get; set; }
        public string ControllerUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb_ControllerMappedRoles> tb_ControllerMappedRoles { get; set; }
    }
}
